---
title: "FinalProject"
author: "Courtney Haas"
date: "11/10/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
diabetes <- read.csv("/Users/Courtney/Desktop/Programming in R/Final Project/diabetes.csv")
library(tidyverse)
```

```{r imputation}
#Changing 0's to NA and imputing to median
diabetes[, 2:6][diabetes[, 2:6] == 0] <- NA

diabetes$SkinThickness[is.na(diabetes$SkinThickness)]<-median(diabetes$SkinThickness,na.rm=TRUE)
diabetes$BloodPressure[is.na(diabetes$BloodPressure)]<-median(diabetes$BloodPressure,na.rm=TRUE)
diabetes$BMI[is.na(diabetes$BMI)]<-median(diabetes$BMI,na.rm=TRUE)
diabetes$Insulin[is.na(diabetes$Insulin)]<-median(diabetes$Insulin,na.rm=TRUE)
diabetes$Glucose[is.na(diabetes$Glucose)]<-median(diabetes$Glucose,na.rm=TRUE)

##Saving new dataset d1
d1 <- diabetes
write.csv(diabetes, "d1.csv",row.names = F)


```

```{r imputation graphics}
##Histogram before imputation
ggplot(diabetes) +
  geom_histogram(mapping=aes(x=BloodPressure),fill="lightskyblue2")+
  theme_light()+
  labs(title = "Histogram for Blood Pressure Before Imputation to Median",
       x = "Blood Pressure (mmHG)",
       y= "Count") +
  theme(plot.title=element_text(hjust=0.50))

##Histogram after imputation
ggplot(d1) +
  geom_histogram(mapping=aes(x=BloodPressure),fill="lightskyblue2") +
  theme_light() +
labs(title = "Histogram for Blood Pressure After Imputation to Median",
     x = "Blood Pressure (mmHG)",
     y= "Count")+
  theme(plot.title=element_text(hjust=0.50))

```



```{r correlations}
##Checking correlations between independent variables
library(GGally)
d1_sub <- d1 %>%
  dplyr::select(Pregnancies,Glucose, BloodPressure, 
                SkinThickness, Insulin, BMI, Age)

GGally::ggcorr(d1_sub, label = T) +
  ggtitle("Visualizing Correlation Matrix as a Heatmap") +
  theme(plot.title=element_text(hjust=0.5))
```


```{r scatterplot}
##Changing the outcome variable for nice graphic legend
do <- d1 %>% 
  dplyr::mutate(Outcome = case_when(Outcome == 0 ~ 'No Diabetes',
                                    Outcome == 1 ~ 'Diabetes'))
##Scatter plot for Glucose and BMI colored by Outcome
ggplot(do) +
  geom_point(mapping = aes(x = Glucose, y = BMI, color= Outcome)) +
  theme_linedraw() +
  labs(x="Glucose (mg/dL)",
       y = "BMI (kg/m^2)",
       title = "Figure 2: Scatterplot for Glucose and BMI by Diabetes Outcome") +
  theme(legend.text = element_text(size=10,face="bold")) +
  theme(plot.title=element_text(hjust=0.5)) +
  scale_color_manual(values=c("lightskyblue2","darkblue")) 

```

```{r logistic regression}
d1$Outcome <- as.numeric(d1$Outcome)
##Logistic Regression model
lmodel <- glm(Outcome ~ SkinThickness + Pregnancies + Glucose + BMI + Age + BloodPressure, data = d1, family = "binomial")
summary(lmodel)

##Pseduo r^2
DescTools::PseudoR2(lmodel,which="McKelveyZavoina")

##Exponentiating coefficients
lmodel %>% 
  broom::tidy(conf.int=T,exponentiate=T)

#VIF
car::vif(lmodel)

##Confidence Interval Plot
plot <- lmodel %>%
  broom::tidy(conf.int=T,exponentiate=T) %>%
  dplyr::mutate(Sig = if_else(p.value < 0.05,"Significant",
                              "Non-Significant")) %>%
  ggplot(aes(x=term,y=estimate)) +
  geom_errorbar(aes(ymin=conf.low,ymax=conf.high,color=factor(Sig)),width=0.1) +
  geom_point(aes(color=factor(Sig))) +
  geom_hline(aes(yintercept = 1),color="black",linetype="dashed") +
  labs(x = "Variable",
       y = "Estimated Exponentiated Coefficient",
       color = "Statistical \n Significance") +
  theme_classic() + coord_flip() +
  ggtitle("Confidence Intervals for Logistic Regression Analysis") +
  theme(plot.title = element_text(hjust=0.5))

plot
library(plotly)
plotly::ggplotly(plot)


```


```{r Sensitivity/Specificity/ROC}
set.seed(12345)

##Creating testing and training datasets
d1$Outcome <- as.numeric(d1$Outcome)
samp <- sample(c("train","test"), nrow(d1), replace = T, prob = c(.7, .3))
d_train <- d1[samp == "train",] #only keep rows where samp = train
d_test <- d1[samp == "test",] 

##Logistic regression with training dataset
testmodel <- glm(Outcome ~ SkinThickness + Pregnancies + Glucose + BMI + Age + BloodPressure, data = d_train, family = "binomial")

##ROC curve
ROSE::roc.curve(testmodel$y,fitted(testmodel),plotit = T) 

##Calculating sensitivity and specificity table at probability > 50%
d_test$pred_probs <- predict.glm(testmodel,newdata=d_test,type="response")
pt <- table(d_test$Outcome,d_test$pred_probs > 0.50)
pt1 <- addmargins(pt)

write.csv(pt1, "sstable.csv",row.names = F)

##Sensitivity
pt[1,1]/sum(pt[1,])

##Specificity
pt[2,2]/sum(pt[2,])

##Using different cutoff points for sensitivity and specificity
cp <- seq(0.20,0.95,by=0.01) 
sn <- vector("double",length(cp)) 
sp <- vector("double",length(cp)) 

for(i in 1:length(cp)){
  
  tab <- table(d_test$Outcome,d_test$pred_probs > cp[i]) 
  
  sp[i] <- ifelse(dim(tab)[2] == 1,0,tab[1,1]/sum(tab[1,]))
  
  sn[i] <- ifelse(dim(tab)[2] == 1,0,tab[2,2]/sum(tab[2,]))
  
}

##Creating plot
ssplot <- ggplot() + 
  geom_line(aes(x = cp, y = sn),color='blue') + #sensitivity in blue
  geom_line(aes(x = cp, y = sp),color='red') + #specificity in red
  theme_classic() + labs(x = "Cut Points",
                         y = "Probabilities") +
  scale_x_continuous(breaks = seq(0.20,0.90,by=0.05))

ssplot

```

```{r table 1}
##removing column 7
d11 <- d1[ -c(7) ]
##only using first five rows
table <- d11[1:5,]
##Creating table for first five rows of dataset
knitr::kable(table,
             caption="First Five Rows of Diabetes Dataset",
             align = "c",
             col.names = c("Pregnancies", "Glucose (mg/dL)", 
             "BloodPressure (mmHG)", "SkinThickness (mm)", 
             "Insulin (muU/ml)","BMI (kg/m^2)", "Age",
             "Outcome")) 
```

```{r table 2}
sstable <- read_csv("/Users/Courtney/Desktop/Programming in R/Final Project/sstable.csv")

##Creating confusion matrix table
knitr::kable(sstable,
             caption="Confusion Matrix",
             align = "c" ) 
```



```{r table 3}
##Saving coefficient table
table1 <- lmodel %>% 
  broom::tidy(conf.int=T,exponentiate=T)

##Selecting the columns to only include
table1 %>% 
  select("term","estimate","std.error","p.value","conf.low", "conf.high")

table2 <- table1[-1,-4]

##creating table with VIF values to each coefficient
v <- tribble(
  ~term, ~VIF,
  "SkinThickness", 1.355471, 
  "Pregnancies", 1.407123,
  "Glucose", 1.052859,
  "BMI", 1.471367,
  "Age", 1.523603,
  "BloodPressure", 1.204516
)

##Merging V and table3
t3 <-merge(x=table2,y=v,by="term",all.x=TRUE)

##Rearranging the order of coefficients based off significance
t4 <- t3[c(5,3,4,1,2,6),]

##Removing row numbers
row.names(t4) <- NULL

##Creating table with coefficients and vif values
knitr::kable(t4,caption="Final Model Variables with P-Value and VIF",
             align = "c", digits=3,
             col.names = c("Term","Estimate","StdError", "P-Value","Conf Low",
             "Conf High", "VIF"))
```



